all: ex1

ex1: ex1.cpp
	@echo "[Building $@ ...]"
	@g++ --std=c++1z ex1.cpp -o ex1
	@echo "[Running $@ ...]"
	@./ex1
	@echo "[Done ...]"

clean:
	@echo "[Deleting binaries ...]"
	@rm -f ./ex1
	@echo "[Done ...]"
	
